In [18]:
import pandas as pd

data1 = pd.read_csv('data_county.csv')
data1.head()

,Unnamed: 0,Data as of,Start Date,End Date,Location,Urban Rural Code,FIPS State,FIPS County,FIPS Code,Indicator,Total deaths,COVID-19 Deaths,Non-Hispanic White,Non-Hispanic Black,Non-Hispanic American Indian or Alaska Native,Non-Hispanic Asian,Non-Hispanic Native Hawaiian or Other Pacific Islander,Hispanic,Other,Urban Rural Description
0,0,09/27/2023,01/01/2020,09/23/2023,"Anchorage Municipality, AK",3,2,20,2020,Distribution of all-cause deaths (%),9439,787,0.568,0.044,0.216,0.058,0.030,0.033,0.050,Medium metro
1,1,09/27/2023,01/01/2020,09/23/2023,"Anchorage Municipality, AK",3,2,20,2020,Distribution of COVID-19 deaths (%),9439,787,0.452,0.037,0.255,0.111,0.074,0.038,0.033,Medium metro
2,2,09/27/2023,01/01/2020,09/23/2023,"Anchorage Municipality, AK",3,2,20,2020,Distribution of population (%),9439,787,0.564,0.052,0.083,0.098,0.031,0.095,0.077,Medium metro
3,3,09/27/2023,01/01/2020,09/23/2023,"Fairbanks North Star Borough, AK",4,2,90,2090,Distribution of all-cause deaths (%),2257,214,0.710,0.024,0.173,0.020,NaN,0.027,0.044,Small metro
4,4,09/27/2023,01/01/2020,09/23/2023,"Fairbanks North Star Borough, AK",4,2,90,2090,Distribution of COVID-19 deaths (%),2257,214,0.626,NaN,0.257,NaN,NaN,NaN,0.056,Small metro

In [19]:
data2 = pd.read_csv('income_per_capita_proc.csv')
data2.head()

   Unnamed: 0     Location     2020     2021     2022  Income_per_Capita
0           0  Autauga, AL  45151.0  48914.0  49391.0       47818.666667
1           1  Baldwin, AL  51230.0  55865.0  56747.0       54614.000000
2           2  Barbour, AL  37111.0  40795.0  40560.0       39488.666667
3           3     Bibb, AL  34938.0  37175.0  37513.0       36542.000000
4           4   Blount, AL  38133.0  42852.0  43744.0       41576.333333

In [22]:
data = pd.merge(data1, data2, on='Location')
data.head()

,Unnamed: 0_x,Data as of,Start Date,End Date,Location,Urban Rural Code,FIPS State,FIPS County,FIPS Code,Indicator,...,Non-Hispanic Asian,Non-Hispanic Native Hawaiian or Other Pacific Islander,Hispanic,Other,Urban Rural Description,Unnamed: 0_y,2020,2021,2022,Income_per_Capita
0,0,09/27/2023,01/01/2020,09/23/2023,"Anchorage Municipality, AK",3,2,20,2020,Distribution of all-cause deaths (%),...,0.058,0.030,0.033,0.050,Medium metro,70,67764.0,72331.0,75506.0,71867.0
1,1,09/27/2023,01/01/2020,09/23/2023,"Anchorage Municipality, AK",3,2,20,2020,Distribution of COVID-19 deaths (%),...,0.111,0.074,0.038,0.033,Medium metro,70,67764.0,72331.0,75506.0,71867.0
2,2,09/27/2023,01/01/2020,09/23/2023,"Anchorage Municipality, AK",3,2,20,2020,Distribution of population (%),...,0.098,0.031,0.095,0.077,Medium metro,70,67764.0,72331.0,75506.0,71867.0
3,3,09/27/2023,01/01/2020,09/23/2023,"Fairbanks North Star Borough, AK",4,2,90,2090,Distribution of all-cause deaths (%),...,0.020,NaN,0.027,0.044,Small metro,77,60410.0,65243.0,67790.0,64481.0
4,4,09/27/2023,01/01/2020,09/23/2023,"Fairbanks North Star Borough, AK",4,2,90,2090,Distribution of COVID-19 deaths (%),...,NaN,NaN,NaN,0.056,Small metro,77,60410.0,65243.0,67790.0,64481.0

In [23]:
data.drop(columns=['Unnamed: 0_x', 'Data as of', 'Unnamed: 0_y'], inplace=True)
data.head()

,Start Date,End Date,Location,Urban Rural Code,FIPS State,FIPS County,FIPS Code,Indicator,Total deaths,COVID-19 Deaths,...,Non-Hispanic American Indian or Alaska Native,Non-Hispanic Asian,Non-Hispanic Native Hawaiian or Other Pacific Islander,Hispanic,Other,Urban Rural Description,2020,2021,2022,Income_per_Capita
0,01/01/2020,09/23/2023,"Anchorage Municipality, AK",3,2,20,2020,Distribution of all-cause deaths (%),9439,787,...,0.216,0.058,0.030,0.033,0.050,Medium metro,67764.0,72331.0,75506.0,71867.0
1,01/01/2020,09/23/2023,"Anchorage Municipality, AK",3,2,20,2020,Distribution of COVID-19 deaths (%),9439,787,...,0.255,0.111,0.074,0.038,0.033,Medium metro,67764.0,72331.0,75506.0,71867.0
2,01/01/2020,09/23/2023,"Anchorage Municipality, AK",3,2,20,2020,Distribution of population (%),9439,787,...,0.083,0.098,0.031,0.095,0.077,Medium metro,67764.0,72331.0,75506.0,71867.0
3,01/01/2020,09/23/2023,"Fairbanks North Star Borough, AK",4,2,90,2090,Distribution of all-cause deaths (%),2257,214,...,0.173,0.020,NaN,0.027,0.044,Small metro,60410.0,65243.0,67790.0,64481.0
4,01/01/2020,09/23/2023,"Fairbanks North Star Borough, AK",4,2,90,2090,Distribution of COVID-19 deaths (%),2257,214,...,0.257,NaN,NaN,NaN,0.056,Small metro,60410.0,65243.0,67790.0,64481.0

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3477 entries, 0 to 3476
Data columns (total 22 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   Start Date                                              3477 non-null   object
 1   End Date                                                3477 non-null   object
 2   Location                                                3477 non-null   object
 3   Urban Rural Code                                        3477 non-null   int64
 4   FIPS State                                              3477 non-null   int64
 5   FIPS County                                             3477 non-null   int64
 6   FIPS Code                                               3477 non-null   int64
 7   Indicator                                               3477 non-null   object
 8   Total deaths                                            3477 non-null   int64
 9   COVID-19 Deaths                                         3477 non-null   int64
 10  Non-Hispanic White                                      3475 non-null   float64
 11  Non-Hispanic Black                                      2857 non-null   float64
 12  Non-Hispanic American Indian or Alaska Native           1822 non-null   float64
 13  Non-Hispanic Asian                                      2140 non-null   float64
 14  Non-Hispanic Native Hawaiian or Other Pacific Islander  1333 non-null   float64
 15  Hispanic                                                2756 non-null   float64
 16  Other                                                   1919 non-null   float64
 17  Urban Rural Description                                 3477 non-null   object
 18  2020                                                    3477 non-null   float64
 19  2021                                                    3477 non-null   float64
 20  2022                                                    3477 non-null   float64
 21  Income_per_Capita                                       3477 non-null   float64
dtypes: float64(11), int64(6), object(5)
memory usage: 597.7+ KB

In [25]:
data.to_csv('completed_data.csv')