In [29]:
import pandas as pd

# Load the dataset
file_path = 'deaths.csv'
data = pd.read_csv(file_path)

In [30]:
data.head()

,Data as of,Start Date,End Date,State,County Name,Urban Rural Code,FIPS State,FIPS County,FIPS Code,Indicator,...,COVID-19 Deaths,Non-Hispanic White,Non-Hispanic Black,Non-Hispanic American Indian or Alaska Native,Non-Hispanic Asian,Non-Hispanic Native Hawaiian or Other Pacific Islander,Hispanic,Other,Urban Rural Description,Footnote
0,09/27/2023,01/01/2020,09/23/2023,AK,Anchorage Municipality,3,2,20,2020,Distribution of all-cause deaths (%),...,787,0.568,0.044,0.216,0.058,0.030,0.033,0.050,Medium metro,NaN
1,09/27/2023,01/01/2020,09/23/2023,AK,Anchorage Municipality,3,2,20,2020,Distribution of COVID-19 deaths (%),...,787,0.452,0.037,0.255,0.111,0.074,0.038,0.033,Medium metro,NaN
2,09/27/2023,01/01/2020,09/23/2023,AK,Anchorage Municipality,3,2,20,2020,Distribution of population (%),...,787,0.564,0.052,0.083,0.098,0.031,0.095,0.077,Medium metro,NaN
3,09/27/2023,01/01/2020,09/23/2023,AK,Fairbanks North Star Borough,4,2,90,2090,Distribution of all-cause deaths (%),...,214,0.710,0.024,0.173,0.020,NaN,0.027,0.044,Small metro,One or more data cells have counts between 1-9...
4,09/27/2023,01/01/2020,09/23/2023,AK,Fairbanks North Star Borough,4,2,90,2090,Distribution of COVID-19 deaths (%),...,214,0.626,NaN,0.257,NaN,NaN,NaN,0.056,Small metro,One or more data cells have counts between 1-9...

In [32]:
data['Location'] = data['County Name'] + ', ' + data['State']
data.tail()

,Data as of,Start Date,End Date,State,County Name,Urban Rural Code,FIPS State,FIPS County,FIPS Code,Indicator,...,Non-Hispanic White,Non-Hispanic Black,Non-Hispanic American Indian or Alaska Native,Non-Hispanic Asian,Non-Hispanic Native Hawaiian or Other Pacific Islander,Hispanic,Other,Urban Rural Description,Footnote,Location
3682,09/27/2023,01/01/2020,09/23/2023,WY,Sheridan County,5,56,33,56033,Distribution of COVID-19 deaths (%),...,0.861,NaN,NaN,NaN,NaN,NaN,NaN,Micropolitan,One or more data cells have counts between 1-9...,"Sheridan County, WY"
3683,09/27/2023,01/01/2020,09/23/2023,WY,Sheridan County,5,56,33,56033,Distribution of population (%),...,0.913,0.007,0.011,0.008,0.001,0.047,0.014,Micropolitan,NaN,"Sheridan County, WY"
3684,09/27/2023,01/01/2020,09/23/2023,WY,Sweetwater County,5,56,37,56037,Distribution of all-cause deaths (%),...,0.885,0.013,0.009,NaN,NaN,0.083,NaN,Micropolitan,One or more data cells have counts between 1-9...,"Sweetwater County, WY"
3685,09/27/2023,01/01/2020,09/23/2023,WY,Sweetwater County,5,56,37,56037,Distribution of COVID-19 deaths (%),...,0.887,NaN,NaN,NaN,NaN,0.096,NaN,Micropolitan,One or more data cells have counts between 1-9...,"Sweetwater County, WY"
3686,09/27/2023,01/01/2020,09/23/2023,WY,Sweetwater County,5,56,37,56037,Distribution of population (%),...,0.792,0.011,0.008,0.009,0.001,0.162,0.017,Micropolitan,NaN,"Sweetwater County, WY"

In [33]:
data.drop('State', axis=1, inplace=True)
data.drop('County Name', axis=1, inplace=True)
data.head()

,Data as of,Start Date,End Date,Urban Rural Code,FIPS State,FIPS County,FIPS Code,Indicator,Total deaths,COVID-19 Deaths,Non-Hispanic White,Non-Hispanic Black,Non-Hispanic American Indian or Alaska Native,Non-Hispanic Asian,Non-Hispanic Native Hawaiian or Other Pacific Islander,Hispanic,Other,Urban Rural Description,Footnote,Location
0,09/27/2023,01/01/2020,09/23/2023,3,2,20,2020,Distribution of all-cause deaths (%),9439,787,0.568,0.044,0.216,0.058,0.030,0.033,0.050,Medium metro,NaN,"Anchorage Municipality, AK"
1,09/27/2023,01/01/2020,09/23/2023,3,2,20,2020,Distribution of COVID-19 deaths (%),9439,787,0.452,0.037,0.255,0.111,0.074,0.038,0.033,Medium metro,NaN,"Anchorage Municipality, AK"
2,09/27/2023,01/01/2020,09/23/2023,3,2,20,2020,Distribution of population (%),9439,787,0.564,0.052,0.083,0.098,0.031,0.095,0.077,Medium metro,NaN,"Anchorage Municipality, AK"
3,09/27/2023,01/01/2020,09/23/2023,4,2,90,2090,Distribution of all-cause deaths (%),2257,214,0.710,0.024,0.173,0.020,NaN,0.027,0.044,Small metro,One or more data cells have counts between 1-9...,"Fairbanks North Star Borough, AK"
4,09/27/2023,01/01/2020,09/23/2023,4,2,90,2090,Distribution of COVID-19 deaths (%),2257,214,0.626,NaN,0.257,NaN,NaN,NaN,0.056,Small metro,One or more data cells have counts between 1-9...,"Fairbanks North Star Borough, AK"

In [34]:
data.columns

Index(['Data as of', 'Start Date', 'End Date', 'Urban Rural Code',
       'FIPS State', 'FIPS County', 'FIPS Code', 'Indicator', 'Total deaths',
       'COVID-19 Deaths', 'Non-Hispanic White', 'Non-Hispanic Black',
       'Non-Hispanic American Indian or Alaska Native', 'Non-Hispanic Asian',
       'Non-Hispanic Native Hawaiian or Other Pacific Islander', 'Hispanic',
       'Other', 'Urban Rural Description', 'Footnote', 'Location'],
      dtype='object')

In [35]:
new_order = ['Data as of', 'Start Date', 'End Date', 'Location', 'Urban Rural Code',
       'FIPS State', 'FIPS County', 'FIPS Code', 'Indicator', 'Total deaths',
       'COVID-19 Deaths', 'Non-Hispanic White', 'Non-Hispanic Black',
       'Non-Hispanic American Indian or Alaska Native', 'Non-Hispanic Asian',
       'Non-Hispanic Native Hawaiian or Other Pacific Islander', 'Hispanic',
       'Other', 'Urban Rural Description']
data = data[new_order]
data.head()

,Data as of,Start Date,End Date,Location,Urban Rural Code,FIPS State,FIPS County,FIPS Code,Indicator,Total deaths,COVID-19 Deaths,Non-Hispanic White,Non-Hispanic Black,Non-Hispanic American Indian or Alaska Native,Non-Hispanic Asian,Non-Hispanic Native Hawaiian or Other Pacific Islander,Hispanic,Other,Urban Rural Description
0,09/27/2023,01/01/2020,09/23/2023,"Anchorage Municipality, AK",3,2,20,2020,Distribution of all-cause deaths (%),9439,787,0.568,0.044,0.216,0.058,0.030,0.033,0.050,Medium metro
1,09/27/2023,01/01/2020,09/23/2023,"Anchorage Municipality, AK",3,2,20,2020,Distribution of COVID-19 deaths (%),9439,787,0.452,0.037,0.255,0.111,0.074,0.038,0.033,Medium metro
2,09/27/2023,01/01/2020,09/23/2023,"Anchorage Municipality, AK",3,2,20,2020,Distribution of population (%),9439,787,0.564,0.052,0.083,0.098,0.031,0.095,0.077,Medium metro
3,09/27/2023,01/01/2020,09/23/2023,"Fairbanks North Star Borough, AK",4,2,90,2090,Distribution of all-cause deaths (%),2257,214,0.710,0.024,0.173,0.020,NaN,0.027,0.044,Small metro
4,09/27/2023,01/01/2020,09/23/2023,"Fairbanks North Star Borough, AK",4,2,90,2090,Distribution of COVID-19 deaths (%),2257,214,0.626,NaN,0.257,NaN,NaN,NaN,0.056,Small metro

In [9]:
data.to_csv('data_county.csv')

In [13]:
file_path2 = 'income_per_capita.csv'
data2 = pd.read_csv(file_path2)
data2.head()

      Location   2020   2021   2022
0  Autauga, AL  45151  48914  49391
1  Baldwin, AL  51230  55865  56747
2  Barbour, AL  37111  40795  40560
3     Bibb, AL  34938  37175  37513
4   Blount, AL  38133  42852  43744

In [16]:
data2['2020'] = pd.to_numeric(data2['2020'], errors='coerce')
data2['2021'] = pd.to_numeric(data2['2021'], errors='coerce')
data2['2022'] = pd.to_numeric(data2['2022'], errors='coerce')

data2['Income_per_Capita'] = data2[['2020', '2021', '2022']].mean(axis=1)
data2.head()

      Location     2020     2021     2022  Income_per_Capita
0  Autauga, AL  45151.0  48914.0  49391.0       47818.666667
1  Baldwin, AL  51230.0  55865.0  56747.0       54614.000000
2  Barbour, AL  37111.0  40795.0  40560.0       39488.666667
3     Bibb, AL  34938.0  37175.0  37513.0       36542.000000
4   Blount, AL  38133.0  42852.0  43744.0       41576.333333

In [18]:
data2.to_csv('income_per_capita_proc.csv')

In [36]:
data['Location'] = data['Location'].str.replace(r'\sCounty,', ',', regex=True)

,Data as of,Start Date,End Date,Location,Urban Rural Code,FIPS State,FIPS County,FIPS Code,Indicator,Total deaths,COVID-19 Deaths,Non-Hispanic White,Non-Hispanic Black,Non-Hispanic American Indian or Alaska Native,Non-Hispanic Asian,Non-Hispanic Native Hawaiian or Other Pacific Islander,Hispanic,Other,Urban Rural Description
0,09/27/2023,01/01/2020,09/23/2023,"Anchorage Municipality, AK",3,2,20,2020,Distribution of all-cause deaths (%),9439,787,0.568,0.044,0.216,0.058,0.030,0.033,0.050,Medium metro
1,09/27/2023,01/01/2020,09/23/2023,"Anchorage Municipality, AK",3,2,20,2020,Distribution of COVID-19 deaths (%),9439,787,0.452,0.037,0.255,0.111,0.074,0.038,0.033,Medium metro
2,09/27/2023,01/01/2020,09/23/2023,"Anchorage Municipality, AK",3,2,20,2020,Distribution of population (%),9439,787,0.564,0.052,0.083,0.098,0.031,0.095,0.077,Medium metro
3,09/27/2023,01/01/2020,09/23/2023,"Fairbanks North Star Borough, AK",4,2,90,2090,Distribution of all-cause deaths (%),2257,214,0.710,0.024,0.173,0.020,NaN,0.027,0.044,Small metro
4,09/27/2023,01/01/2020,09/23/2023,"Fairbanks North Star Borough, AK",4,2,90,2090,Distribution of COVID-19 deaths (%),2257,214,0.626,NaN,0.257,NaN,NaN,NaN,0.056,Small metro

In [37]:
data.tail()

,Data as of,Start Date,End Date,Location,Urban Rural Code,FIPS State,FIPS County,FIPS Code,Indicator,Total deaths,COVID-19 Deaths,Non-Hispanic White,Non-Hispanic Black,Non-Hispanic American Indian or Alaska Native,Non-Hispanic Asian,Non-Hispanic Native Hawaiian or Other Pacific Islander,Hispanic,Other,Urban Rural Description
3682,09/27/2023,01/01/2020,09/23/2023,"Sheridan, WY",5,56,33,56033,Distribution of COVID-19 deaths (%),1247,101,0.861,NaN,NaN,NaN,NaN,NaN,NaN,Micropolitan
3683,09/27/2023,01/01/2020,09/23/2023,"Sheridan, WY",5,56,33,56033,Distribution of population (%),1247,101,0.913,0.007,0.011,0.008,0.001,0.047,0.014,Micropolitan
3684,09/27/2023,01/01/2020,09/23/2023,"Sweetwater, WY",5,56,37,56037,Distribution of all-cause deaths (%),1265,115,0.885,0.013,0.009,NaN,NaN,0.083,NaN,Micropolitan
3685,09/27/2023,01/01/2020,09/23/2023,"Sweetwater, WY",5,56,37,56037,Distribution of COVID-19 deaths (%),1265,115,0.887,NaN,NaN,NaN,NaN,0.096,NaN,Micropolitan
3686,09/27/2023,01/01/2020,09/23/2023,"Sweetwater, WY",5,56,37,56037,Distribution of population (%),1265,115,0.792,0.011,0.008,0.009,0.001,0.162,0.017,Micropolitan

In [38]:
data.to_csv('data_county.csv')